apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: moci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: moci
    app.kubernetes.io/part-of: byoc-app-oxce
  name: moci
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: moci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: moci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-yxsy-tenant/byoc-app-oxce/moci@sha256:17a567a7e997504f59e5ad7f71ab7a6ee7f45f266a1004114d922d5bff5d02a5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
